version: "3"

networks:
  mynetwork:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - mynetwork

  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket
    image: ticket
    ports:
      - "3000:3000"
    networks:
      - mynetwork
